# 服务配置
Server:
  # 运行模式
  RunMode: debug
  # 服务端口
  HttpPort: 8080
  # 读取超时时间
  ReadTimeout: 60
  # 写入超时时间
  WriteTimeout: 60

# 数据库配置
Database:
  # 数据库类型
  DBType: mysql
  # 用户名
  Username: root
  # 密码
  Password: root
  # 主机
  Host: "127.0.0.1:3306"
  # 数据库名
  DBName: casbin_test
  # 表前缀
  TablePrefix: ops_
  # 字符集
  Charset: utf8
  # 解析
  ParseTime: True
  # idle时间
  MaxIdleTime: 10
  # 最大连接数
  MaxOpenConn: 30